-- Newsletter Subscribers Table
CREATE TABLE public.newsletter_subscribers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  email text NOT NULL UNIQUE,
  status text DEFAULT 'active', -- 'active', 'unsubscribed'
  source text, -- 'homepage', 'blog', 'services', etc.
  CONSTRAINT valid_email CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$')
);

-- Enable Row Level Security
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;

-- Create index for faster email lookups
CREATE INDEX idx_newsletter_email ON public.newsletter_subscribers(email);

-- Policies for newsletter subscribers
CREATE POLICY "Anyone can insert newsletter subscriptions."
  ON newsletter_subscribers FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Only admins can view newsletter subscribers."
  ON newsletter_subscribers FOR SELECT
  USING ( auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin') );

CREATE POLICY "Only admins can update newsletter subscribers."
  ON newsletter_subscribers FOR UPDATE
  USING ( auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin') );

CREATE POLICY "Only admins can delete newsletter subscribers."
  ON newsletter_subscribers FOR DELETE
  USING ( auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin') );
