-- Job Applications Table
CREATE TABLE public.job_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  position text NOT NULL,
  experience text,
  education text,
  skills text,
  message text,
  cv_url text,
  status text DEFAULT 'new' -- 'new', 'reviewed', 'interviewed', 'hired', 'rejected'
);

-- Enable Row Level Security
ALTER TABLE public.job_applications ENABLE ROW LEVEL SECURITY;

-- Policies for job applications
CREATE POLICY "Anyone can insert job applications."
  ON job_applications FOR INSERT
  WITH CHECK ( true );

CREATE POLICY "Only admins can view job applications."
  ON job_applications FOR SELECT
  USING ( auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin') );

CREATE POLICY "Only admins can update job applications."
  ON job_applications FOR UPDATE
  USING ( auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin') );

-- Create storage bucket for CVs
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('cvs', 'cvs', true, 5242880, ARRAY['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']);

-- Storage policies for CV uploads
CREATE POLICY "Anyone can upload CVs."
  ON storage.objects FOR INSERT
  WITH CHECK ( bucket_id = 'cvs' );

CREATE POLICY "CVs are publicly accessible."
  ON storage.objects FOR SELECT
  USING ( bucket_id = 'cvs' );

CREATE POLICY "Only admins can delete CVs."
  ON storage.objects FOR DELETE
  USING ( auth.uid() IN (SELECT id FROM profiles WHERE role = 'admin') );